import React, { useEffect, useState } from "react";
import { useHistory } from "react-router-dom";
import FlightSelect from "./FlightSelect";
import Form from "./Form";

const initialState = { seat: "", givenName: "", surname: "", email: "" };

const SeatSelect = ({ setReservationId }) => {
  const history = useHistory();
  const [flightNumber, setFlightNumber] = useState(null);
  const [formData, setFormData] = useState(initialState);
  const [disabled, setDisabled] = useState(true);
  const [subStatus, setSubStatus] = useState("idle");

  useEffect(() => {
    // This hook is listening to state changes and verifying whether or not all
    // of the form data is filled out.
    Object.values(formData).includes("") || flightNumber === ""
      ? setDisabled(true)
      : setDisabled(false);
  }, [flightNumber, formData, setDisabled]);

  // sets the flight number based on the chosen option of the drop down
  const handleFlightSelect = (ev) => {
    setFlightNumber(ev.target.value);
    setFormData({ ...formData, flight: ev.target.value });
  };

  // set the seat based on the one chosen in the form
  const handleSeatSelect = (seatId) => {
    setFormData({ ...formData, seat: seatId });
  };

  // sets the reservation information based on the form input values
  const handleChange = (val, item) => {
    setFormData({ ...formData, [item]: val });
  };

  // validates the email based on whether or not it has an @ in it
  const validateEmail = () => {
    const emailParts = formData.email.split("@");
    return (
      emailParts.length === 2 &&
      emailParts[0].length > 0 &&
      emailParts[1].length > 0
    );
  };

  const handleSubmit = (ev) => {
    ev.preventDefault();
    if (validateEmail()) {
      // TODO: Send data to the server for validation/submission
      fetch("/reservations/add", {
        method: "POST",
        body: JSON.stringify(formData),
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
      })
        .then((res) => res.json())
        // deconstruct the result into the variables that we need
        .then(({ data, message, status }) => {
          if (status === 201) {
            console.log(message);
            // TODO: if 201, add reservation id (received from server) to localStorage
            localStorage.setItem("customerId", JSON.stringify(data.id));
            // setReservationId to the new id generated by the back end that we fetched after sending the form input data there
            setReservationId(data.id);
            // TODO: if 201, redirect to /confirmed (push)
            history.push("/confirmed");
          } else {
            // TODO: if error from server, show error to user (stretch goal)
            console.log(status, message, data);
          }
        });
    }
  };

  return (
    <>
      <FlightSelect
        flightNumber={flightNumber}
        handleFlightSelect={handleFlightSelect}
      />
      <h2>Select your seat and Provide your information!</h2>
      <Form
        flightNumber={flightNumber}
        formData={formData}
        handleChange={handleChange}
        handleSeatSelect={handleSeatSelect}
        handleSubmit={handleSubmit}
        disabled={disabled}
        subStatus={subStatus}
      />
    </>
  );
};

export default SeatSelect;
